<div id="" style="background:#CCCCCC"">                    
  		<table  width="80%">
  		  <tr>
  			<td align="center">
	  			<a href="ExportCourseReportToExcel.php"><img src="images/excel.jpeg" align="absmiddle"/> <font size="1">Export to Excel</font></a>
	  		</td>
	  		<td align="center">
	  			<!--<a href="ExportCourseReportToPDF.php"><img src="images/pdf.jpeg" align="absmiddle"/> <font size="1">Export to PDF</font></a>-->
	  		</td>
	  		<td align="center">
	  			<a href="ExportCourseReportToWord.php"><img src="images/word.jpeg" align="absmiddle"/> <font size="1">Export to Word 2003/2007</font></a>
	  		</td>	  			
	  	  </tr>
  		</table>         
</div>