<div id="" style="background:#CCCCCC"">                    
  		<table  width="80%">
  		  <tr>
  			<td align="center">
	  			<a href="ExportInstructorReportToExcel.php"><img src="images/excel.jpeg" align="absmiddle"/> <font size="1">Export to Excel</font></a>
	  		</td>
	  		<td align="center">
	  			<a href="html2pdf_report/ExportInstructorReportToPDF.php"><img src="images/pdf.jpeg" align="absmiddle"/> <font size="1">Export to PDF</font></a>
	  		</td>
	  		<td align="center">
	  			<a href="ExportInstructorReportToWord.php"><img src="images/word.jpeg" align="absmiddle"/> <font size="1">Export to Word 2003/2007</font></a>
	  		</td>	  			
	  	  </tr>
  		</table>         
</div>