<?php
	@session_start();	
	include_once("classes/DBConnection.php");
	include_once("classes/Parttimer.php");
	include_once("classes/AcademicRank.php");
	
	$deptIdNum = $_SESSION['deptId'];
	//print("inside ext parttimer info file academicUnitId is $deptIdNum");
	//now i need to get the auto generated id and should make it visible to the who ever doing the data insertion
	//first i need to get the department
	$query = "SELECT * FROM tblAcademicUnit WHERE id = '$deptIdNum'";
	//print($query);	
	$result = DBConnection::readFromDatabase($query);
	$resultRow = mysql_fetch_object($result);
	$deptName = $resultRow->academic_unit_name;
	$abbrivatedDeptName = substr($deptName,0,3);//only pic the first 3 chars...i doonoooo talk with wondisho bout it
	//now its time to get the auto generated id from the database
	$autoId = Parttimer::getExternalParttimerAutoGeneratedId($abbrivatedDeptName);
	
	
	print("<form name='frmregisterparttimer' method='post' action='SaveParttimer.php'>");
	print("<table border='0' width='100%'>");
	print("<caption style='background:lightblue'>External Parttimer Information</caption>");
		print("<tr>");
			print("<td>");
				print("First Name");
			print("</td>");			
			print("<td>");
				print("<input type='text' name='txtfirstname' size='12'/>");
			print("</td>");
			
			print("<td>");
				print("Email");
			print("</td>");			
			print("<td>");
				print("<input type='text' name='txtemail' size='12'/>");
			print("</td>");
			
			print("<td>");
				print("Academic Rank");
			print("</td>");			
			print("<td>");
				
					$resultRank = AcademicRank::getAllAcademicRanks();
					print("<select name='slctinstructorlevel' onChange='checkAndChangeColor(this.value,id)'>");
					print("<option value='' selected='selected'>--Select--</option>");
					while($resultRankRow = mysql_fetch_object($resultRank))
					{
						print("<option value='$resultRankRow->rank_name'>$resultRankRow->rank_name</option>");
					}//end while
					print("</select>");
				
			print("</td>");
			print("</tr>");
			print("<tr>");
				print("<td>");
					print("Father Name");
				print("</td>");			
				print("<td>");
					print("<input type='text' name='txtlastname' size='12'/>");
				print("</td>");
				
				print("<td>");
					print("Mobile Phone");
				print("</td>");			
				print("<td>");
					print("<input type='text' name='txtmobilephone' size='12'/>");
				print("</td>");
				
				print("<td>");
					print("Specialization");
				print("</td>");			
				print("<td>");
					print("<input type='text' name='txtspecialization' size='12'/>");
				print("</td>");
			print("</tr>");
			print("<tr>");
				print("<td>");
					print("Organization");
				print("</td>");
				print("<td>");
					print("<input type='text' name='txtorganization' size='12'/>");
				print("</td>");
				print("<td>");
					print("Parttimer Id");
				print("</td>");
				print("<td>");
					print("<input type='text' name='txtparttimerid' size='12' value='$autoId'/>");
				print("</td>");
			print("</tr>");
			print("<tr>");
				print("<td colspan='6' align='right'>");
					print("<input type='submit' value='Add' class='button'/>");
				print("</td>");
			print("</tr>");			
		print("</table>");
	print("</form>");

	//$academicUnitId = $_SESSION['deptId'];
	$query = "SELECT * FROM tblParttimer WHERE academic_unit_id = '$deptIdNum'";
	$result = DBConnection::readFromDatabase($query);
	
	print("<caption>List of Registered Parttmers</caption>");
	print("<table border='0' width='100%'>");
	print("<caption style='background: lightblue'>List of Registered Parttmers</caption>");
		print("<tr style='background:lightblue'>");
			print("<td align='center'>");
				print("<font size='2'><strong>Parttimer Id</strong></font>");
			print("</td>");
			
			print("<td align='center'>");
				print("<font size='2'><strong>Full Name</strong></font>");
			print("</td>");
			
			print("<td align='center'>");
				print("<font size='2'><strong>Email</strong></font>");
			print("</td>");
			
			print("<td align='center'>");
				print("<font size='2'><strong>Academic Rank</strong></font>");
			print("</td>");
			
			print("<td align='center'>");
				print("<font size='2'><strong>Mobile Phone</strong></font>");
			print("</td>");
			
			print("<td align='center'>");
				print("<font size='2'><strong>Specialization</strong></font>");
			print("</td>");
			
			print("<td align='center'>");
				print("<font size='2'><strong>Organization</strong></font>");
			print("</td>");
		print("</tr>");
		
	$ctr = 1;
	while($resultRow = mysql_fetch_object($result))
	{
		   if($ctr % 2 == 0)
		   {
			  print("<tr style='background:#ded7fe'>");
			}
			else
			{
			  print("<tr style='background:#ecfdfe'>");
			}
			
			print("<td>");
				print("<font size='2'>".$resultRow->parttimer_id."</font>");
			print("</td>");					
			print("<td>");
				print("<font size='2'>".$resultRow->first_name." ".$resultRow->last_name."</font>");			
			print("</td>");
			print("<td>");
				print("<font size='2'>".$resultRow->email."</font>");
			print("</td>");
			print("<td align='center'>");
				print("<font size='2'>".$resultRow->instructor_level."</font>");
			print("</td>");
			print("<td>");
				print("<font size='2'>".$resultRow->mobile_phone."</font>");
			print("</td>");
			print("<td>");
				print("<font size='2'>".$resultRow->specialization."</font>");
			print("</td>");
			print("<td>");
				print("<font size='2'>".$resultRow->organization."</font>");
			print("</td>");		
		print("</tr>");
		$ctr++;
	}
	print("</table>");
?>