
 <!-- footer starts here -->
<div class="footer">
		<!--<img src="images/nav.png" align="top" width="100%" height="30"/>-->		
		<p>
			&copy; 2010 <strong>Academic Staff Load Managment System</strong> Addis Ababa University&nbsp;&nbsp;
			Web Application Developed By: Mahder Alemayehu & Wondwossen Mulugeta. <br/>
			<strong>email:</strong> mahdera@yahoo.com | <strong>Tele:</strong> +251-911-150129 |
			<strong>email:</strong> wondisho@yahoo.com | <strong>Tele:</strong> +251-911-607338			
		</p>		
</div>
