
 <!-- footer starts here -->
<div class="footer">	
		<p>
			&copy; 2010 <strong>Academic Staff Load Managment System</strong> Addis Ababa University&nbsp;&nbsp;
			Website Design by: Mahder Alemayehu & Wondwossen Mulugeta. <br/>
			<strong>email:</strong> mahdera@yahoo.com | <strong>Tele:</strong> +251-911-150129 |
			<strong>email:</strong> wondisho@yahoo.com | <strong>Tele:</strong> +251-911-607338		
			<br /><a href="admin/AdminLogin.php"><img src="images/admin.gif" /> Administrator</a> |
			<a href="CollegeUserLogin.php">College User</a>
		</p>		
</div>
