<div id="manageDiv" style="background:#CCCCCC"">                    
  		<table  width="100%">
  		  <tr>
  			<td align="center">
	  			<a href="ChangeUserName.php"><img src="images/new.png" align="absmiddle"/> <font size="1">Change my username</font></a>
	  		</td>
	  		<td align="center">
	  			<a href="ChangePassword.php"><img src="images/view.png" align="absmiddle"/> <font size="1">Change my password</font></a>
	  		</td>	  		
	  	  </tr>
  		</table>         
</div>