
<div id="" style="background:#CCCCCC"">                    
  		<table  width="100%">
  		  <tr>
  			<td align="center">
	  			<a href="UserArea.php"><img src="images/back.jpeg" align="absmiddle"/> <font size="1">Back to Home</font></a>
	  		</td>
	  		<td align="center">
	  			<a href="ShowInstructorReport.php"><img src="images/instructorreport.jpeg" align="absmiddle"/> <font size="1">Instructor Report</font></a>
	  		</td>
	  		<td align="center">
	  			<a href="ShowCourseReport.php"><img src="images/coursereport.jpeg" align="absmiddle"/> <font size="1">Course Report</font></a>
	  		</td>
	  		<td align="center">
	  			<a href="ShowLoadReportFinal.php"><img src="images/loadreport.jpeg" align="absmiddle"/> <font size="1">Load Report</font></a>
	  		</td>	  		
	  	  </tr>
  		</table>         
</div>