<ul>
	<li><a href="ExportInstructorReportToExcel.php"><img src="images/excel.jpeg" align="absmiddle"/> <font size="1">Export to Excel</font></a></li>
	<li><a href="ExportInstructorReportToExcel.php"><img src="images/excel.jpeg" align="absmiddle"/> <font size="1">Export to Excel</font></a></li>
	<li><a href="ExportInstructorReportToWord.php"><img src="images/word.jpeg" align="absmiddle"/> <font size="1">Export to Word 2003/2007</font></a></li>
</ul>