<?php
	include_once("DBConnection.php");
	
	class Parttimer{
		private $id;
		private $parttimerId;
		private $firstName;
		private $lastName;
		private $email;
		private $mobilePhone;
		private $instuctorLevel;		
		private $specialization;
		private $organization;	
		private $academicUnitId;	
		
		public function Parttimer($parttimerId,$firstName,$lastName,$email,$mobilePhone,$instructorLevel,$specialization,$organization,$academicUnitId)
		{
			$this->setParttimerId($parttimerId);			
			$this->setFirstName($firstName);
			$this->setLastName($lastName);
			$this->setEmail($email);
			$this->setMobilePhone($mobilePhone);
			$this->setInstructorLevel($instructorLevel);			
			$this->setSpecialization($specialization);
			$this->setOrganization($organization);
			$this->setAcademicUnitId($academicUnitId);
		}	
		
		public function setAcademicUnitId($academicUnitId)
		{
			$this->academicUnitId = $academicUnitId;
		}
		
		public function setParttimerId($parttimerId)
		{
			$this->parttimerId = $parttimerId;
		}
		
		public function setSpecialization($specialization)
		{
			$this->specialization = $specialization;
		}
		
		public function setFirstName($firstName)
		{
			$this->firstName = $firstName;
		}
		
		public function setLastName($lastName)
		{
			$this->lastName = $lastName;
		}
		
		public function setEmail($email)
		{
			$this->email = $email;
		}
		
		public function setMobilePhone($mobilePhone)
		{
			$this->mobilePhone = $mobilePhone;
		}
		
		public function setInstructorLevel($instructorLevel)
		{
			$this->instructorLevel = $instructorLevel;
		}
		
		public function setOrganization($organization)
		{
			$this->organization = $organization;
		}
		
		public function getAcademicUnitId()
		{
			return $this->academicUnitId;
		}
		
		public function getParttimerId()
		{
			return $this->parttimerId;
		}
		
		public function getServiceYear()
		{
			return $this->serviceYear;
		}
		
		public function getSpecialization()
		{
			return $this->specialization;
		}
		
		public function getInstructorId()
		{
			return $this->instructorId;
		}
		
		public function getFirstName()
		{
			return $this->firstName;
		}	
		
		public function getLastName()
		{
			return $this->lastName;
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		public function getMobilePhone()
		{
			return $this->mobilePhone;
		}
		
		public function getInstructorLevel()
		{
			return $this->instructorLevel;
		}
		
		public function getOrganization()
		{
			return $this->organization;
		}
		
		public function addParttimer()
		{
			try{
				$query = "INSERT INTO tblParttimer VALUES(0,'$this->parttimerId','$this->firstName','$this->lastName','$this->email','$this->mobilePhone','$this->instructorLevel','$this->specialization','$this->organization','$this->academicUnitId')";
				DBConnection::executeQuery($query);
			}catch(Exception $e){
				$e->__toString();
			}
		}
		
		public static function deleteParttimer($id)
		{
			try{
				$query = "DELETE FROM tblParttimer WHERE parttimer_id = '$id'";
				//print($query);				
				DBConnection::executeQuery($query);
			}catch(Exception $e){
				$e->__toString();
			}
		}
		
		public static function updateParttimer($parttimerId,$firstName,$lastName,$email,$mobilePhone,$instructorLevel,$spcialization,$organization,$academicUnitId)
		{
			try{
				$query = "UPDATE tblParttimer SET first_name = '$firstName', last_name = '$lastName', email = '$email', mobile_phone = '$mobilePhone', instructor_level = '$instructorLevel', specialization = '$spcialization', organization = '$organization', academic_unit_id = '$academicUnitId' WHERE parttimer_id = '$parttimerId'";
				//print($query);
				DBConnection::executeQuery($query);
			}catch(Exception $e){
				$e->__toString();
			}
		}
		
		public static function getNextParttimerIdNumber()
    	{
        $query = "SELECT MAX(id) FROM tblParttimer";
        $result=DBConnection::ExecuteQuery($query);

        if($result)//if the above read function is sucessfull
        {
            $row=mysql_fetch_array($result);
            $nextId=$row[0]+1;
            return $nextId;
        }
        else
            return 0;
    	}
    	
    	public static function getExternalParttimerAutoGeneratedId($dept)
    	{
    		$prefix = "PT";
    		$nextAutoId = Parttimer::getNextParttimerIdNumber();
    		$composedId = $prefix."/".$dept."/".$nextAutoId;
    		return $composedId;
    	}
    	
    	public static function getParttimerDetail($parttimerId){
    		try{
    			$query = "SELECT * FROM tblParttimer WHERE parttimer_id = '$parttimerId'";
    			//print($query);
    			$result = DBConnection::executeQuery($query);
    			$resultRow = mysql_fetch_object($result);
    			return $resultRow;
			}catch(Exception $e){
				$e->__toString();
			}    		
    	}
		
	}//end class
?>