<div>
	<table border="0" width="100%">
		<tr style="background:lightblue">
			<td>
				<img src="images/home.gif" border="0" align="absmiddle"/> <a href="AdminArea.php"><font size="2">Back To Admin Home</font></a> |
				<img src="images/search.jpeg" border="0" align="absmiddle"/> <a href="InstructorDetailSearch.php"><font size="2">Instructor Detail Load</font></a>				
			</td>
			<hr/>
		</tr>
	</table>
</div>