<div align="left" style="background:#CCCCCC">                    
  		<table width="80%">
  			<tr>  				
		  		<td align="center">
		  			<a href="#.php" onclick="showListOfAcademicUnitsWhoCompletedLoadInformation();"><img src="images/view.png" align="absmiddle"/> <font size="1">View Academic Units with Complet Load Information</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="#.php" onclick="showListOfAcademicUnitsWhoCompletedLoadInformationForEdit();"><img src="images/edit.gif" align="absmiddle"/> <font size="1">Edit Academic Units with Complet Load Information</font></a>
		  		</td>		  		
		  	</tr>
  		</table>         
</div>