
<div align="left" style="background:#CCCCCC">                    
  		<table border="0" width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddAdminPosition.php"><img src="images/new.png" align="absmiddle"> <font size="1">Add Admin Position</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewAdminPosition.php"><img src="images/view.png" align="absmiddle"> <font size="1">View Admin Position</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditAdminPosition.php"><img src="images/edit.gif" align="absmiddle"> <font size="1">Edit Admin Position</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteAdminPosition.php"><img src="images/ImgDelete.gif" align="absmiddle"> <font size="1">Delete Admin Position</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>