
<div align="left" style="background:#CCCCCC">                    
  		<table width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddAcademicUnit.php"><img src="images/new.png" align="absmiddle"> <font size="1">Add Academic Unit</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewAcademicUnit.php"><img src="images/view.png" align="absmiddle"> <font size="1">View Academic Unit</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditAcademicUnit.php"><img src="images/edit.gif" align="absmiddle"> <font size="1">Edit Academic Unit</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteAcademicUnit.php"><img src="images/ImgDelete.gif" align="absmiddle"> <font size="1">Delete Academic Unit</font></a>
		  		</td>
		  		<td align="center">  		
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>