<div align="left" style="background:#CCCCCC">
	<table border="0" width="80%">
		<tr>
			<td align="center">
				<a href="AddSemester.php"><font size="1"><img src="images/addsemester.jpeg" border="0" align="absmiddle"/> Add Semester</font></a>
			</td>
			<td align="center">
				<a href="ViewSemester.php"><font size="1"><img src="images/viewsemester.jpeg" border="0" align="absmiddle"/> View Semester</font></a>
			</td>
		</tr>
	</table>
</div>