<div align="left" style="background:#CCCCCC">                    
  		<table border="0" width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddTeachingCommitmentRateLookup.php"><img src="images/new.png" align="absmiddle"> <font size="1">Add Commitment Rate Lookup</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewTeachingCommitmentRateLookup.php"><img src="images/view.png" align="absmiddle"> <font size="1">View Commitment Rate Lookup</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditTeachingCommitmentRateLookup.php"><img src="images/edit.gif" align="absmiddle"> <font size="1">Edit Commitment Rate Lookup</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteTeachingCommitmentRateLookup.php"><img src="images/ImgDelete.gif" align="absmiddle"> <font size="1">Delete Commitment Rate Lookup</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>