<div align="left" style="background:#CCCCCC">                    
  		<table width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddInstructor.php"><img src="images/new.png" align="absmiddle"/> <font size="1">Add Instructor</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewInstructor.php"><img src="images/view.png" align="absmiddle"/> <font size="1">View Instructor</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditInstructor.php"><img src="images/edit.gif" align="absmiddle"/> <font size="1">Edit Instructor</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteInstructor.php"><img src="images/ImgDelete.gif" align="absmiddle"/> <font size="1">Delete Instructor</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="SearchInstructor.php"><img src="images/b_search.png" align="absmiddle"/> <font size="1">Search Instructor</font></a>
		  		</td>
		  		<td align="center">  		
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"/> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>