
<div align="left" style="background:#CCCCCC">                    
  		<table border="0" width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddDeliveryRate.php"><img src="images/new.png" align="absmiddle"> <font size="1">Add Delivery Rate</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewDeliveryRate.php"><img src="images/view.png" align="absmiddle"> <font size="1">View Delivery Rate</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditDeliveryRate.php"><img src="images/edit.gif" align="absmiddle"> <font size="1">Edit Delivery Rate</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteDeliveryRate.php"><img src="images/ImgDelete.gif" align="absmiddle"> <font size="1">Delete Delivery Rate</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>