
<div align="left" style="background:#CCCCCC">                    
  		<table border="0" width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddTeachingCommitment.php"><img src="images/new.png" align="absmiddle"> <font size="1">Add Teaching Commitment</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewTeachingCommitment.php"><img src="images/view.png" align="absmiddle"> <font size="1">View Teaching Commitment</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditTeachingCommitment.php"><img src="images/edit.gif" align="absmiddle"> <font size="1">Edit Teaching Commitment</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteTeachingCommitment.php"><img src="images/ImgDelete.gif" align="absmiddle"> <font size="1">Delete Teaching Commitment</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>