
<div align="left" style="background:#CCCCCC">                    
  		<table border="0" width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddCourseDelivery.php"><img src="images/new.png" align="absmiddle"> <font size="1">Add Course Delivery</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewCourseDelivery.php"><img src="images/view.png" align="absmiddle"> <font size="1">View Course Delivery</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditCourseDelivery.php"><img src="images/edit.gif" align="absmiddle"> <font size="1">Edit Course Delivery</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteCourseDelivery.php"><img src="images/ImgDelete.gif" align="absmiddle"> <font size="1">Delete Course Delivery</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>