
<div align="left" style="background:#CCCCCC">                    
  		<table border="0" width="80%">
  			<tr>
  				<td align="center">
		  			<a href="AddAcademicRank.php"><img src="images/new.png" align="absmiddle"> <font size="1">Add Academic Rank</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="ViewAcademicRank.php"><img src="images/view.png" align="absmiddle"> <font size="1">View Academic Rank</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="EditAcademicRank.php"><img src="images/edit.gif" align="absmiddle"> <font size="1">Edit Academic Rank</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="DeleteAcademicRank.php"><img src="images/ImgDelete.gif" align="absmiddle"> <font size="1">Delete Academic Rank</font></a>
		  		</td>
		  		<td align="center">
		  			<a href="LogOff.php"><img src="images/logout.gif" align="absmiddle"> <font size="1">Logout</font></a>
		  		</td>
		  	</tr>
  		</table>         
</div>